name: Continuous Integration | Dev Build Test & Push Dev Version

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  packages: write

jobs:
  test-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Build Test
        run: |
          bun install
          bun run build

  builder:
    runs-on: ubuntu-22.04
    needs: [test-build]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Github Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node (for versioning)
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Get Version
        id: getversion
        run: |
          VERSION=$(node ./dev-versioning)
          FULL_TAG="v${VERSION}"
          echo "IMAGE_TAG=${FULL_TAG}" >> $GITHUB_OUTPUT
          echo "Extracted Version Tag: ${FULL_TAG}"
      
      - name: Setup QEMU Action
        uses: docker/setup-qemu-action@v3
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest

      - name: Login GCHR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.bun
          platforms: linux/amd64
          push: true
          build-args: |
            TARGET=production
          tags: |
            ghcr.io/${{ github.repository }}:dev
            ghcr.io/${{ github.repository }}:dev-${{ steps.getversion.outputs.IMAGE_TAG }}
          provenance: false